name: Patrice Michellon
favicon: null
layout_spectrum: 0.50066
typography_spectrum: 0.34223
title: 'Patrice Michellon | Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c1c1bf'
    - '#999589'
    - '#5b5a55'
    - '#252523'
  brandStrength: 1
  lightness: 0.9322337869089097
  saturation: 0.706409057835117
  rhythmicContrast: 0.4101726794615388
purpose: []
